### ISSUE TITLE
老哥你这个cate cata可还好哈哈

### ISSUE THREAD

**Issue by n8v79a** [Skactor/behinder_source#1]
![image](https://user-images.githubusercontent.com/19548313/90864928-2a3da680-e3c4-11ea-9c3c-99ee4a3c9d4f.png)
![image](https://user-images.githubusercontent.com/19548313/90864931-2e69c400-e3c4-11ea-88c2-697c63f22197.png)

**Comment by n8v79a** [comment]
原本是cate我给改了cata了

**Comment by Slzdude** [comment]
收到，我改一下
